### PR TITLE
Fix WebResponse timing out

### LINKED ISSUE #163: Webresponse timing out when doing multiple requests since NGitLab 6.11.0
Since the version 6.11.0, there seems to be an issue where doing multiple requests (for functional tests for example) times out when getting the response. 

Versions before 6.11.0 worked perfectly fine.

### PR DESCRIPTION
**Pull request by mchanyeechoy**
I found that putting the yield outside the while loop fixes the timing out problem.

Fix #163

### CODE REVIEW

File: NGitLab/Impl/HttpRequestor.cs [hunk 1]
```diff
@@ -162,14 +163,17 @@ public override async IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken c
                     using var streamReader = new StreamReader(stream);
                     var responseText = await streamReader.ReadToEndAsync().ConfigureAwait(false);
                     var deserialized = SimpleJson.DeserializeObject<T[]>(responseText);
-                    foreach (var item in deserialized)
-                        yield return item;
+                    buffer.AddRange(deserialized);
```
Comment (meziantou) [inline NGitLab/Impl/HttpRequestor.cs]: By using a list, you cannot stream the response. You'll enumerate all pages before returning the first result to the caller. 

I think you should try to first change the scope of the response / stream by using explicit using block (`using (...) {}`), so you ensure the response and stream are disposed before returning the items.

**Review by meziantou — CHANGES_REQUESTED** [review]

**Comment by meziantou** [comment]
Do you think it would be possible to add a test to ensure there is no regression on this one?

**Review by meziantou — APPROVED** [review]
